### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by haesookim** [haesookim/interface-programming-team1#4]
- [x] 데이터저장
- [x] 카테고리들에 따른 그림 변경
- [x] 리스트뷰에서 월 변경
- [x] 리스트뷰 셀 변동

우선순위 하
- [x] 데이터 불충분시 입력저지
- [x] 카테고리 커스터마이징
- [x] 시간 픽뷰에 지우기 추가
- [ ] copy paste기능 막기
- [x] 그외 그래픽 폴리시
